"""baseline_schema_22_tables

Revision ID: 364a0d60c198
Revises: 
Create Date: 2026-10-05 09:32:31.286642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '364a0d60c198'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    from backend.app.core.database import Base
    import backend.app.models
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
